### ISSUE TITLE
Missing space in @media(...) throws exception

### ISSUE THREAD

**Issue by voehl** [sabberworm/PHP-CSS-Parser#104] opened 2016-06-25 22:04 UTC
Unfortunately, when parsing stylesheets without the space in "@ media(" the parser throws an UnexpectedTokenException.

Example:
```
<?php
use Sabberworm\CSS\Parser;
require '../vendor/autoload.php';

// This works:
(new Parser('@media (min-width: 768px){.class{color:red}}'))->parse();

// This throws an exception: 'Identifier expected. Got “: 768”'
(new Parser('@media(min-width: 768px){.class{color:red}}'))->parse();
```

**Comment by sabberworm** [comment] 2016-06-27 16:47
Closing as duplicate of #75

**Closed by sabberworm** 2016-06-27 16:47 UTC
