### ISSUE TITLE
Can't composer update on Linux Ubuntu corrupt error

### ISSUE THREAD

**Issue by Hugo-Trial** [sabberworm/PHP-CSS-Parser#403] opened 2022-10-27 12:41 UTC
![image](https://user-images.githubusercontent.com/94128151/198286889-183684ee-7fdd-40f0-a783-023897d0ea21.png)

**Comment by oliverklee** [comment] 2022-10-27 13:22
I'm using Composer 2.4.4 and Git 2.34.1 on Ubuntu 22.04.

**Comment by oliverklee** [comment] 2022-10-27 13:44
No, sorry, no idea.

Closing as this seems to not be an issues caused by this package.

**Closed by oliverklee** 2022-10-27 13:44 UTC

**Comment by Hugo-Trial** [comment] 2022-10-27 13:57
You're completely right @oliverklee. I was fairly new to devops when I did that :)
Thanks a lot for your time, sorry to have created an issue for the wrong reasons. Hopefully it will help someone through Google searches :)
