### ISSUE TITLE
Uncaught exception 'Sabberworm\CSS\Parsing\SourceException'

### ISSUE THREAD

**Issue by ossinkine** [sabberworm/PHP-CSS-Parser#107] opened 2016-07-11 19:34 UTC
This code throws `SourceException` with message `Unopened { [line no: 5]`
```php
$css = <<<CSS
@media(min-width:480px){
    body{
        background-color:lightgreen;
    }
}
CSS;

$parser = new Sabberworm\CSS\Parser($css);
$css = $parser->parse();
```

It seems the parser expects a space after `@media`.

**Comment by sabberworm** [comment] 2016-07-11 19:35
Closing as duplicate of #75.

**Closed by sabberworm** 2016-07-11 19:35 UTC
