### ISSUE TITLE
var function inside color functions cannot be parsed

### ISSUE THREAD

**Issue by digilist** [sabberworm/PHP-CSS-Parser#196] opened 2020-07-10 13:51 UTC
Thank you for this library. I just started playing around with it and it works really good so far.

But I just noticed that parsing a rule like the following fails:

```css
a {
    background: rgba(var(--some-rgb) , 0.1);
}
```

The reason is that the var is inside the rgba function. If strict mode is enabled, this error is given: `Token “,” (1) not found. Got “var(-”.`

But this is valid CSS, see here for example: https://stackoverflow.com/a/41265350/1044527

UPDATE: fails also for `rgb(var(--some-rgb))`

**Comment by westonruter** [comment] 2020-07-10 17:41
I believe this is a duplicate of #186.

**Closed** 2020-07-21 18:32 UTC
